#!/usr/bin/env bash

if ! basename "$PWD" | grep "malware" &>/dev/null; then
    echo "Please run this in the go/src/malware folder"
    exit 1
fi
 protoc -I  . --go_out=plugins=grpc:. common/messages/messages.proto
go build -o waterpistol malware/cmd
