#!/usr/bin/env bash

set -eu -o pipefail

if ! hash terraform > /dev/null 2>&1; then
    echo "Terraform is missing from your machine, please install it." >&2
    exit 1
fi

export C2_AMI="${C2_AMI:-ami-09b42976632b27e9b}"
export C2_KEYPAIR_NAME="${C2_KEYPAIR_NAME:-$(whoami)@$(hostname -s)}"
export C2_KEYPAIR_PRIV_PATH="./id_c2"

if [[ ! -f "${C2_KEYPAIR_PRIV_PATH}" ]]; then
    echo "Missing c2 ssh keypair, generating." >&2

    ssh-keygen -t rsa -f "${C2_KEYPAIR_PRIV_PATH}" -N ''
fi

export C2_KEYPAIR_PUB_PATH="${C2_KEYPAIR_PRIV_PATH}.pub"
export C2_KEYPAIR_PUB="$(cat ${C2_KEYPAIR_PUB_PATH})"

cat "malware.tf_" | envsubst > malware.tf 

terraform init >&2

(echo "yes" | terraform apply >&2) || exit $?

terraform output c2_ip
