#!/usr/bin/env bash

set -eu -o pipefail

if ! hash terraform > /dev/null 2>&1; then
    echo "Terraform is missing from your machine, please install it." >&2
    exit 1
fi

(echo "yes" | terraform destroy >&2) || exit $?
